### ISSUE TITLE
Possibility to "flush" actions programmatically?

### ISSUE THREAD

**Issue by afiller** [Nozbe/WatermelonDB#595] opened 2019-12-19 17:45 UTC
Although I'm using batching in my code, I realized that a lot of actions are queued when it comes to higher load in our react native app. Therefore I asked myself, if there's a way to "flush" the action queue? I would do the same when the app is sent to the background or requested to quit by the operating system.

Thanks in advance!

Andreas

**Comment by radex** [comment] 2019-12-20 09:02
@afiller I’m not entirely sure if I understand your question, so:

- `batch` (and other) calls are completed once the Promise resolves.
- Actions are a mechanism to prevent concurrent database writes (this is necessary to maintain integrity in an asynchronous database), those are not like database _transactions_, which are only committed to disk once the transaction is done.

Is that helpful? Or do you mean something else by „flush”?

**Comment by afiller** [comment] 2019-12-20 10:20
Hi @radex, thank you for clarifying this. I only wondered, because I always get the message that 30/50/100 actions are still in the queue when I have the app running in debug mode and perform several actions/batches after each other. Under these conditions it also happens that I loose actions when I quit/kill the app to early, so it seems some actions are still in the queue. It seems as if one transaction is veeeery very slow in debug mode. On the real device it seems to be not the case.

Do you have an idea why this could be the case that it's soooo slow on iOS and Android when I start it in debug mode? 
The source for one of our transactions attached:

```
await database.action(async () => {
    const index = await messagesColl.query(Q.where('old_id', 'index')).fetch()

    let indexCreateOrUpdate = null
    if (index.length === 0) {
      indexCreateOrUpdate = messagesColl.prepareCreate((message) => {
        message.oldId = 'index'
        message.oldContent = indexContent
      })
    } else {
      indexCreateOrUpdate = index[0].prepareUpdate((message) => {
        message.oldContent = indexContent
      })
    }

    const messageCreate = messagesColl.prepareCreate((message) => {
      message.oldId = messageId
      message.oldContent = messageContent
    })

    await database.batch(...[indexCreateOrUpdate, messageCreate])
  })
  log.debug('Message added.')
```

May it be a problem with redux which we also have in the app?

Thanks in advance for your reply!

**Comment by radex** [comment] 2019-12-20 11:08
I don’t know. You have to profile your app :) It’s very likely that the issue is not with 🍉 but with your react / redux code.

in general, you want to avoid a situation where you have dozens or hundreds of actions pending. I’d recommend looking into whether you can merge them into a single / a couple of batches/actions. That’ll be significantly faster.

**Comment by diegolmello** [comment] 2019-12-20 12:30
What about actions that come from a socket?
Think in a chat app (😜).
Each message received from socket is a batch of 5 DMLs.
If the channel have 10 people talking at the same time, a queue will be created.
And, you know... people flood sometimes :)

**Comment by afiller** [comment] 2019-12-20 13:10
Yea, @diegolmello...it's a bit this way in our case. Nevertheless, since we need to ensure data stability at all times, our app is now waiting for the Promises to resolve. In release build you don't feel anything. Only in debug-country you feel lags while the updates are running on the database.

**Comment by radex** [comment] 2019-12-20 13:27
@diegolmello What I'd do in your case is a simple throttle/debounce/window operation, e.g. Rx's https://www.learnrxjs.io/operators/transformation/windowtime.html (you can also do it in 20 lines of vanilla JS by scheduling a small timeout) to gather all messages within a short window (e.g. 50ms), and make a single database operation to add them all at once.

There is indeed a small latency involved in making native operations in React Native (and in executing sqlite transactions), so you definitely want to avoid having tens or hundreds of unrelated batches/actions a second with Watermelon - and actually _batch_ them together for best performance.

It's also possible that there is some strange 🍉 bottleneck that we could fix, but you have to do the work on your own app to profile it and identify what exactly causes the slowdown

**Comment by diegolmello** [comment] 2019-12-20 18:30
@radex Yep, it would work.
I didn't try it because it's a hell of a change though.
Will bisync changes make it any better?

**Comment by radex** [comment] 2020-01-13 10:57
> Will bisync changes make it any better?

@diegolmello maybe, I'm not sure. You can check a prerelease version of watermelon and add `synchronous: true` option to SQLiteAdapter

**Closed** 2020-08-01 11:59 UTC
Labels: wontfix
