### ISSUE TITLE
Diagnostic error: Unsafe name 'undefined' not allowed (not a string)

### ISSUE THREAD

**Issue by KartikDevarde2601** [Nozbe/WatermelonDB#1760] opened 2024-03-13 08:39 UTC
**Error**
_ ERROR  Error fetching nurses: [Diagnostic error: Unsafe name 'undefined' not allowed (not a string)]_
**Observable**

```
const enhance = withObservables(['route'], ({route}) => ({
  nurse: route.params.nurselogin.observe(),
  patients: route.params.nurselogin.patients.observe(),
}));

export default enhance(UserListScreen);

```
**Schema**
````
export const mySchema = appSchema({
  version: 4,
  tables: [
    tableSchema({
      name: 'nurses',
      columns: [
        {name: 'name', type: 'string'},
        {name: 'email', type: 'string'},
        {name: 'role', type: 'string'},
        {name: 'doctorId', type: 'string'},
        {name: 'doctorName', type: 'string'},
        {name: 'created_at', type: 'number'},
        {name: 'updated_at', type: 'number'},
      ],

    }),
    tableSchema({
      name: 'patients',
      columns: [
        {name: 'name', type: 'string'},
        {name: 'age', type: 'number'},
        {name: 'gender', type: 'string'},
        {name: 'race', type: 'string'},
        {name: 'height', type: 'number'},
        {name: 'weight', type: 'number'},
        {name: 'BMI', type: 'number'},
        {name: 'bloodGroup', type: 'string'},
        {name: 'email', type: 'string'},
        {name: 'role', type: 'string'},
        {name: 'nurse_id', type: 'string', isIndexed: true},
        {name: 'nurseName', type: 'string'},
        {name: 'created_at', type: 'number'},
        {name: 'updated_at', type: 'number'},
      ],
    }),`
```

**Models**
```
 
![image](https://github.com/Nozbe/WatermelonDB/assets/126013799/d2713822-9294-4f7b-9f58-155b437094c0)

**Comment by lucaswitch** [comment] 2024-03-17 03:33
Duplicate of #1761

**Closed** 2024-03-27 20:33 UTC
