### ISSUE TITLE
[Bug][iOS] 'jsi/jsi.h' file not found

### ISSUE THREAD

**Issue by kesha-antonov** [Nozbe/WatermelonDB#691] opened 2020-05-19 10:05 UTC
Hi!

After update from `0.16.0` to `0.16.1` I get this error:
```
In file included from /node_modules/@nozbe/watermelondb/native/ios/WatermelonDB/JSLockPerfHack.mm:1:

/node_modules/@nozbe/watermelondb/native/ios/WatermelonDB/JSLockPerfHack.h:3:10: fatal error: 'jsi/jsi.h' file not found
#include <jsi/jsi.h>
         ^~~~~~~~~~~
1 error generated.
```

<img width="946" alt="Screenshot 2020-05-19 at 13 03 05" src="https://user-images.githubusercontent.com/11584712/82313646-4f8bd480-99d1-11ea-9746-30346a05281f.png">

**Comment by radex** [comment] 2020-05-19 10:09
@kesha-antonov RN version? are you using cocoa pods or classic Xcode projects?

**Comment by kesha-antonov** [comment] 2020-05-19 11:16
@radex 

"react-native": "0.63.0-rc.1"

I'm using Pods

**Comment by radex** [comment] 2020-05-19 14:09
Okay. I will investigate sometime soon. Sorry about this - for now, just use 0.16.0 ;)

**Comment by kesha-antonov** [comment] 2020-05-19 16:06
> Okay. I will investigate sometime soon. Sorry about this - for now, just use 0.16.0 ;)

thanks!

**Comment by hussamkurd** [comment] 2020-05-20 13:29
Same here

**Comment by hussamkurd** [comment] 2020-05-22 08:03
@radex 
even with 0.16.0
<img width="597" alt="Screen Shot 2020-05-22 at 11 02 33 AM" src="https://user-images.githubusercontent.com/15825449/82645652-e21fb400-9c1b-11ea-8881-6aaaa244473c.png">

**Comment by thiagobrez** [comment] 2020-05-22 15:39
Same here, downgrading to 0.16.0 works.

`react-native`: 0.61.5
Using pods

**Comment by zeo1986** [comment] 2020-05-22 19:22
have the same error with 0.16.0 =(((

**Comment by mtford90** [comment] 2020-05-23 11:51
Yep - seems to effect >=0.16.

Had to drop down to 0.15 here.

**Comment by iamclaytonray** [comment] 2020-05-23 16:45
@mtford90 - would you happen to have a repo that you could make public? I've struggled all morning to get this lib running properly 😅

**Comment by mtford90** [comment] 2020-05-23 20:14
@iamclaytonray I don't have a public repo I can show you but I've had a rather wonky experience getting this library running myself.

0.15.0
- Runs in dev mode, doesn't run in release mode

0.16.0,0.16.1
- Will not run in either debug mode or release mode

0.16.1-0
- Runs in both debug & release mode

So I'm not sure what changed 0.16.1-0 onwards and it's obviously some kind of alpha build, but it's currently the only one that's working for me, so perhaps try that version and see what happens?

**Comment by annie-elequin** [comment] 2020-05-23 22:40
Unfortunately I'm getting this error with all three of these values 😔 

I just added React Native Web, which may be contributing - I'm running RN version 0.62.2

**Comment by j92** [comment] 2020-05-24 08:18
I can confirm that `0.16.1-0` still works.

**Comment by zeo1986** [comment] 2020-05-25 18:50
@j92 @mtford90  thanks !!! 0.16.1-0 working for me

**Comment by davidsonsns** [comment] 2020-05-27 20:41
@j92 `0.16.1-0` worked here as well! Tks.

FYI: tried running it with version `0.17.0-2`, just for curiosity, and I got the same issue.

**Comment by radex** [comment] 2020-05-28 06:35
@davidsonsns on RN 0.62?

**Comment by davidsonsns** [comment] 2020-05-28 11:24
Sorry, I forgot to put this info. So yep.
I'm using `0.62`, being more specific version `0.62.2`

**Comment by victorbutler** [comment] 2020-05-28 22:47
I had this issue too. For this I added a Header Source Path to the xcode project target build settings.
1. Find file `node_modules/@noze/watermelondb/native/ios/WatermelonDB.xcodeproj` and open it in Xcode
2. Add `$(SRCROOT)/../../../../../ios/Pods/Headers/Public/React-jsi` **recursive** path to your settings like in the pic below.
![Screen Shot 2020-05-28 at 4 34 25 PM](https://user-images.githubusercontent.com/1063420/83200821-66cd6f00-a101-11ea-9f11-3caebfcbfabe.png)
3. Click off the popover window to make it disappear and try to build ios again.

Notes: This only works if you have the `ios` directory in your project root. So if you have it set up differently, it will still fail. This might not be the correct way to include these headers, but it's what I found. `jsi/jsi.h` is all over the place. In the `react-native` package it's inside `ReactCommon` but I had more issues when I added that path.

![image](https://user-images.githubusercontent.com/1063420/83201368-94ff7e80-a102-11ea-9904-38e189fd8922.png)

@radex I tried to fork and create a PR for this but it looks like master isn't up to date with the 0.17.0-2 tag so I had some trouble testing.

**Comment by finom** [comment] 2020-06-02 09:24
@victorbutler worked for me, thank you!

**Comment by finom** [comment] 2020-06-16 11:08
I'm getting the error every time when I reinstall dependencies by removing node_modules folder. @victorbutler fix is helpful but that bug needs to be definitely fixed.

**Comment by radex** [comment] 2020-06-16 12:49
@finom use `patch-package` to make the patch persistent. Watermelon v0.17 will have the patch

**Comment by finom** [comment] 2020-06-16 20:45
@radex did you mean to run `npx patch-package @nozbe/watermelondb`? It says 
```
⁉️  Not creating patch file for package '@nozbe/watermelondb'
⁉️  There don't appear to be any changes.
```

**Comment by diegolmello** [comment] 2020-06-17 12:36
@finom You have to change the files directly on `node_modules` folder as mentioned on https://github.com/Nozbe/WatermelonDB/issues/691#issuecomment-635648157 and then run `patch-package`.
It's going to create a patch like we ours [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/patches/%40nozbe%2Bwatermelondb%2B0.16.2.patch)

**Comment by radex** [comment] 2020-10-05 09:17
Closing this now, as fix has been out for a long time

**Closed by radex** 2020-10-05 09:17 UTC
