### ISSUE TITLE
rambdax.contains is undefined

### ISSUE THREAD

**Issue by ShaharyarMaroof** [Nozbe/WatermelonDB#475] opened 2019-08-30 06:36 UTC
Hi I am trying to setup tableSchema as per the [documentation](https://nozbe.github.io/WatermelonDB/Installation.html).

```
import { appSchema,tableSchema } from '@nozbe/watermelondb'

export default appSchema({
	version: 1,
	tables: [
		tableSchema({
			name: 'todos',
			columns: [
				{ name: 'todo', type: 'string' },
				{ name: 'date', type: 'string' }
			]
		})
	]
})
```

When I run the application I get the following error:
![Screenshot_1567146758](https://user-images.githubusercontent.com/10959027/63998154-e4843000-cb19-11e9-9e94-094ebe034daf.png)

package.json dependencies
    "@nozbe/watermelondb": "^0.14.0",
    "@nozbe/with-observables": "^1.0.5",

package.json devDependencies
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/plugin-proposal-decorators": "^7.4.4",
    "@babel/plugin-proposal-export-namespace-from": "^7.5.2",
    "@babel/plugin-transform-runtime": "^7.5.5",

Can you please let me know what is wrong here? Thanks in advance.

**Comment by rkrajewski** [comment] 2019-08-30 09:07
Hi @ShaharyarMaroof, please check existing issues before reporting new one?
Closing this as duplicate of https://github.com/Nozbe/WatermelonDB/issues/471

**Closed by rkrajewski** 2019-08-30 09:07 UTC
