### ISSUE TITLE
Problem in the sync "Pull" process?

### ISSUE THREAD

**Issue by Tharinducn** [Nozbe/WatermelonDB#854] opened 2020-11-01 10:58 UTC
I have noticed in the sync process that the updated is run before the created process. What if after the lastPulledAt a record is created and the same has been updated in the back-end. I am sending the changes object as below.

```
customers": {
  "created": [
    {
      "id": "0000-11eb-adc1-0242ac120002",
      "name": "name 1",
      "created_at": 1604224465,
      "updated_at": 1604224485,
  ],
  "updated": [
    {
      "id": "0000-11eb-adc1-0242ac120002",
      "name": "name 1",
      "created_at": 1604224465,
      "updated_at": 1604224485,
    }
  ],
  "deleted": []
}
```

Currently, this logs an error 
`[Sync] Server wants client to update record customers#0000-11eb-adc1-0242ac120002, but it doesn't exist locally. This could be a serious bug. Will create record instead.`

**Comment by bralandealmeida** [comment] 2021-02-16 11:52
Facing the same here. Did you find any solution?

**Comment by radex** [comment] 2021-03-24 09:08
@Tharinducn Receiving an object with the same ID more than once during pull is unexpected and not up to WatermelonDB's sync protocol spec. Why do you need to send it twice? Just send the created version.

Given no reply for last comment, I assume the issue is out of date, closing

**Closed by radex** 2021-03-24 09:08 UTC
