### ISSUE TITLE
Unable to resolve module `rxjs-compat/operators/map`

### ISSUE THREAD

**Issue by alexandrumic** [Nozbe/WatermelonDB#843] opened 2020-10-12 11:39 UTC
Hi,

I've just updated to `v0.20.0` and I encounter the following error:
```
error: Error: Unable to resolve module `rxjs-compat/operators/map` from `node_modules/@nozbe/with-observables/node_modules/rxjs/operators/map.js`: rxjs-compat/operators/map could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
```

What have I tried so far:
* I have add in `Podfile` the following: 
`pod 'React-jsi', :path => "../node_modules/react-native/ReactCommon/jsi", :modular_headers => true` 
`pod 'WatermelonDB', :path => '../node_modules/@nozbe/watermelondb'` and ran again `pod install`
* I have cleared the cache using the following commands:
`watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf $TMPDIR/metro* && rm -rf $TMPDIR/haste-*`
`rm -rf ~/.rncache`
`rm -rf ~/Library/Caches/com.facebook.ReactNativeBuild`
`rm -rf ~/Library/Developer/Xcode/DerivedData/*`
`rm -rf ~/Library/Caches/CocoaPod`
* I have removed `node_modules` and installed the dependencies again

Do you know what might be the issue?

Thanks

**Comment by alexandrumic** [comment] 2020-10-12 16:32
Hello @leo-tavares!

I was thinking about this solution too, but according to the [latest changelog](https://nozbe.github.io/WatermelonDB/CHANGELOG.html#020---2020-10-05) it states that:
> Interal RxJS imports have been refactor such that rxjs-compat should never be used now

so I think that library should not be used anymore and maybe that is a forgotten dependency 🤔 . 
Maybe @radex can confirm this or give us more details.

Thank you! 👍

**Comment by radex** [comment] 2020-10-13 10:36
Yeah, the error message says it all:

```
error: Error: Unable to resolve module `rxjs-compat/operators/map` from `node_modules/@nozbe/with-observables/node_modules/rxjs/operators/map.js`: rxjs-compat/operators/map could not be found within the project.
```
the problem is with withObservables which is still misconfigured and doesn't explicitly have rxjs-compat as a dependency. I'd appreciate a quick PR fixing the imports there.

**Comment by leo-tavares** [comment] 2020-10-13 16:37
Hello @radex and @alexandrumic !

I open a [pull request](https://github.com/Nozbe/withObservables/pull/96),I hope it helps :smile:

**Comment by radex** [comment] 2020-10-19 08:01
merged and published, thanks!

**Closed by radex** 2020-10-19 08:01 UTC

**Comment by Mohamed-kassim** [comment] 2020-10-19 15:12
Error: Unable to resolve module `rxjs-compat/observable/from` from `node_modules/rxjs/observable/from.js`: rxjs-compat/observable/from could not be found within the project.
----
this one still exists until now

**Comment by leo-tavares** [comment] 2020-10-20 14:24
Hello @Mohamed-kassim Just for you to **test**! Install directly from the master.

`yarn add https://github.com/Nozbe/withObservables.git#master`
